name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubantu-latest

    steps:

    - name: Checkout Code
      uses: actions/Checkout@v3

    - name: Setup Python
      uses: actions/Setup-python@v4  
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest        


          